import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy | SideKick Studioss",
  description:
    "How SideKick Studioss collects, uses, and protects account information, campaign data, and the lead data processed on behalf of our customers.",
};

const sections: LegalSection[] = [
  {
    title: "Information we collect",
    paragraphs: [
      "We collect the information needed to run your account and your campaigns:",
    ],
    bullets: [
      "Account details such as your name, email address, and workspace settings.",
      "Campaign configuration: the templates you use, budgets, schedules, and service areas you set.",
      "Lead data submitted through your Meta lead forms, which we process on your behalf: typically a lead's name, contact details, and message.",
      "Connection data for integrations you authorize, such as Meta or supported CRM providers.",
      "Basic usage data, such as pages viewed and device information, to keep the product working and improve it.",
    ],
  },
  {
    title: "How we use it",
    paragraphs: ["We use this information to:"],
    bullets: [
      "Operate your workspace, launch and manage the campaigns you configure.",
      "Deliver leads to you through the dashboard, email alerts, CSV export, and the CRM connections you set up.",
      "Send service communications about your account, trial, and billing.",
      "Improve the product and troubleshoot issues.",
    ],
  },
  {
    title: "Lead data belongs to your business",
    paragraphs: [
      "Leads generated by your campaigns are your customer relationships, not ours. We do not sell lead data, use it for our own marketing, or share it across workspaces. When you export or hand leads off to your CRM, you control where that data lives.",
    ],
  },
  {
    title: "Who we share information with",
    paragraphs: ["We share information only with:"],
    bullets: [
      "Service providers that host the platform, store data, or send email on our behalf.",
      "Meta and the CRM platforms you explicitly connect, to run campaigns and deliver leads.",
      "Professional advisors or authorities when the law requires it.",
    ],
  },
  {
    title: "Your rights",
    paragraphs: ["You can:"],
    bullets: [
      "Request access to the personal information we hold about you.",
      "Ask us to correct inaccurate information or delete your account data.",
      "Disconnect any integration at any time from workspace settings.",
      "Contact us with any question about how your data or your leads' data is handled.",
    ],
  },
  {
    title: "Contact",
    paragraphs: [
      "Questions about this policy can be sent through the support form in the app or from the public support page. We respond to every privacy request.",
    ],
  },
];

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      intro="How SideKick Studioss collects, uses, and protects your account information, your campaign data, and the lead data we process on behalf of your business."
      updated="Last updated: June 2026"
      sections={sections}
      crossLink={{ label: "Terms of Service", href: "/terms" }}
    />
  );
}
