import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service | SideKick Studioss",
  description:
    "Terms of Service for the SideKick Studioss platform: subscriptions, the free trial, campaign publishing, lead data, and acceptable use.",
};

const sections: LegalSection[] = [
  {
    title: "The service",
    paragraphs: [
      "SideKick Studioss is a software platform that lets businesses launch Meta advertising campaigns from templates, capture the resulting leads, and manage follow-up. By creating an account you agree to these terms on behalf of yourself or the business you represent.",
    ],
  },
  {
    title: "Trial, subscription, and billing",
    paragraphs: [
      "New accounts start with a 14-day free trial of the full platform. If you cancel before the trial ends, you are not charged. After the trial, the subscription renews monthly at the listed price until you cancel. You can cancel at any time from account settings; cancellation takes effect at the end of the current billing period.",
    ],
  },
  {
    title: "Your campaigns and ad spend",
    paragraphs: [
      "Campaigns launched through SideKick run in your own Meta ad account, under your authorization. Ad spend is billed to you by Meta and is separate from your SideKick subscription. You are responsible for the offers, claims, and creative you publish, and for complying with Meta's advertising policies and the laws that apply to your business.",
    ],
  },
  {
    title: "Your data and your leads",
    paragraphs: [
      "Lead data generated by your campaigns belongs to your business. We process it to deliver the service: showing leads in your dashboard, sending alerts, and handing data to integrations you connect. Details are in the Privacy Policy.",
    ],
  },
  {
    title: "Acceptable use",
    paragraphs: ["You agree not to:"],
    bullets: [
      "Run campaigns that are deceptive, unlawful, or violate Meta's advertising policies.",
      "Upload content you do not have the rights to use.",
      "Attempt to access other workspaces, disrupt the service, or resell access without an agreement with us.",
    ],
  },
  {
    title: "Availability and changes",
    paragraphs: [
      "We work to keep SideKick available and improving, and we may add, change, or retire features over time. If we make a change that materially reduces what your subscription includes, we will tell you before your next renewal.",
    ],
  },
  {
    title: "Liability",
    paragraphs: [
      "To the fullest extent allowed by law, SideKick Studioss is not responsible for indirect or incidental losses arising from use of the platform, including campaign performance, lead quality, or outages of third-party services such as Meta. Our liability is limited to the subscription fees you paid in the twelve months before the claim, unless the law requires otherwise.",
    ],
  },
  {
    title: "Contact",
    paragraphs: [
      "Questions about these terms can be sent through the support form in the app or from the public support page.",
    ],
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      intro="The agreement between your business and SideKick Studioss: the subscription, the free trial, campaign publishing, and how lead data is handled."
      updated="Last updated: June 2026"
      sections={sections}
      crossLink={{ label: "Privacy Policy", href: "/privacy" }}
    />
  );
}
